### ISSUE TITLE
downloaded code, compiled and ran it. Couldn't get it to work At All. Depending on what is typed the combo either shows all the names or none of them.

### ISSUE THREAD

**Issue by jbesemer** [vain0x/DotNetKit.Wpf.AutoCompleteComboBox#6]

**Comment by croddin** [comment]
It looks like this is because in the demo program the whole list of persons is stored in one person object because of a line endings issue. In person.cs Environment.NewLine is used but the file has \n line endings instead of \r\n. 

To fix the demo, change the code that defines allPersons in:
DotNetKit.Wpf.AutoCompleteComboBox.Demo\Data\Person.cs

to 

```
static readonly IReadOnlyList<Person> allPersons =
            source.Split(new[] { Environment.NewLine, "\n" }, StringSplitOptions.RemoveEmptyEntries)
            .Select((name, i) => new Person(i + 1L, name))
            .ToArray();
```

I can send a pull request if this is being maintained.

**Comment by jbesemer** [comment]
Works great. Thanks.
